In [27]:
import numpy as np
import pandas as pd

In [28]:
df=pd.read_csv('weatherAUS.csv')

In [29]:
df

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145455,2017-06-21,Uluru,2.8,23.4,0.0,NaN,NaN,E,31.0,SE,...,51.0,24.0,1024.6,1020.3,NaN,NaN,10.1,22.4,No,No
145456,2017-06-22,Uluru,3.6,25.3,0.0,NaN,NaN,NNW,22.0,SE,...,56.0,21.0,1023.5,1019.1,NaN,NaN,10.9,24.5,No,No
145457,2017-06-23,Uluru,5.4,26.9,0.0,NaN,NaN,N,37.0,SE,...,53.0,24.0,1021.0,1016.8,NaN,NaN,12.5,26.1,No,No
145458,2017-06-24,Uluru,7.8,27.0,0.0,NaN,NaN,SE,28.0,SSE,...,51.0,24.0,1019.4,1016.5,3.0,2.0,15.1,26.0,No,No
145459,2017-06-25,Uluru,14.9,NaN,0.0,NaN,NaN,NaN,NaN,ESE,...,62.0,36.0,1020.2,1017.9,8.0,8.0,15.0,20.9,No,NaN

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145460 entries, 0 to 145459
Data columns (total 23 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Date           145460 non-null  object
 1   Location       145460 non-null  object
 2   MinTemp        143975 non-null  float64
 3   MaxTemp        144199 non-null  float64
 4   Rainfall       142199 non-null  float64
 5   Evaporation    82670 non-null   float64
 6   Sunshine       75625 non-null   float64
 7   WindGustDir    135134 non-null  object
 8   WindGustSpeed  135197 non-null  float64
 9   WindDir9am     134894 non-null  object
 10  WindDir3pm     141232 non-null  object
 11  WindSpeed9am   143693 non-null  float64
 12  WindSpeed3pm   142398 non-null  float64
 13  Humidity9am    142806 non-null  float64
 14  Humidity3pm    140953 non-null  float64
 15  Pressure9am    130395 non-null  float64
 16  Pressure3pm    130432 non-null  float64
 17  Cloud9am       89572 non-null   float64
 18  Cloud3pm       86102 non-null   float64
 19  Temp9am        143693 non-null  float64
 20  Temp3pm        141851 non-null  float64
 21  RainToday      142199 non-null  object
 22  RainTomorrow   142193 non-null  object
dtypes: float64(16), object(7)
memory usage: 25.5+ MB

In [31]:
df.drop(['Date', 'Location', 'Evaporation', 'Sunshine', 'WindGustDir', 'WindDir9am','WindDir3pm', 'Cloud3pm','Cloud9am'], axis=1, inplace=True)

In [32]:
df.head(50)

,MinTemp,MaxTemp,Rainfall,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,13.4,22.9,0.6,44.0,20.0,24.0,71.0,22.0,1007.7,1007.1,16.9,21.8,No,No
1,7.4,25.1,0.0,44.0,4.0,22.0,44.0,25.0,1010.6,1007.8,17.2,24.3,No,No
2,12.9,25.7,0.0,46.0,19.0,26.0,38.0,30.0,1007.6,1008.7,21.0,23.2,No,No
3,9.2,28.0,0.0,24.0,11.0,9.0,45.0,16.0,1017.6,1012.8,18.1,26.5,No,No
4,17.5,32.3,1.0,41.0,7.0,20.0,82.0,33.0,1010.8,1006.0,17.8,29.7,No,No
5,14.6,29.7,0.2,56.0,19.0,24.0,55.0,23.0,1009.2,1005.4,20.6,28.9,No,No
6,14.3,25.0,0.0,50.0,20.0,24.0,49.0,19.0,1009.6,1008.2,18.1,24.6,No,No
7,7.7,26.7,0.0,35.0,6.0,17.0,48.0,19.0,1013.4,1010.1,16.3,25.5,No,No
8,9.7,31.9,0.0,80.0,7.0,28.0,42.0,9.0,1008.9,1003.6,18.3,30.2,No,Yes
9,13.1,30.1,1.4,28.0,15.0,11.0,58.0,27.0,1007.0,1005.7,20.1,28.2,Yes,No
10,13.4,30.4,0.0,30.0,17.0,6.0,48.0,22.0,1011.8,1008.7,20.4,28.8,No,Yes
11,15.9,21.7,2.2,31.0,15.0,13.0,89.0,91.0,1010.5,1004.2,15.9,17.0,Yes,Yes
12,15.9,18.6,15.6,61.0,28.0,28.0,76.0,93.0,994.3,993.0,17.4,15.8,Yes,Yes
13,12.6,21.0,3.6,44.0,24.0,20.0,65.0,43.0,1001.2,1001.8,15.8,19.8,Yes,No
14,8.4,24.6,0.0,NaN,4.0,30.0,57.0,32.0,1009.7,1008.7,15.9,23.5,No,NaN
15,9.8,27.7,NaN,50.0,NaN,22.0,50.0,28.0,1013.4,1010.3,17.3,26.2,NaN,No
16,14.1,20.9,0.0,22.0,11.0,9.0,69.0,82.0,1012.2,1010.4,17.2,18.1,No,Yes
17,13.5,22.9,16.8,63.0,6.0,20.0,80.0,65.0,1005.8,1002.2,18.0,21.5,Yes,Yes
18,11.2,22.5,10.6,43.0,24.0,17.0,47.0,32.0,1009.4,1009.7,15.5,21.0,Yes,No
19,9.8,25.6,0.0,26.0,17.0,6.0,45.0,26.0,1019.2,1017.1,15.8,23.2,No,No
20,11.5,29.3,0.0,24.0,9.0,9.0,56.0,28.0,1019.3,1014.8,19.1,27.3,No,No
21,17.1,33.0,0.0,43.0,17.0,22.0,38.0,28.0,1013.6,1008.1,24.5,31.6,No,No
22,20.5,31.8,0.0,41.0,19.0,20.0,54.0,24.0,1007.8,1005.7,23.8,30.8,No,No
23,15.3,30.9,0.0,33.0,6.0,13.0,55.0,23.0,1011.0,1008.2,20.9,29.0,No,No
24,12.6,32.4,0.0,43.0,4.0,19.0,49.0,17.0,1012.9,1010.1,21.5,31.2,No,No
25,16.2,33.9,0.0,35.0,9.0,13.0,45.0,19.0,1010.9,1007.6,23.2,33.0,No,No
26,16.9,33.0,0.0,57.0,0.0,26.0,41.0,28.0,1006.8,1003.6,26.6,31.2,No,No
27,20.1,32.7,0.0,48.0,13.0,30.0,56.0,15.0,1005.2,1001.7,24.6,32.1,No,No
28,19.7,27.2,0.0,46.0,19.0,30.0,49.0,22.0,1004.8,1004.2,21.6,26.1,No,Yes
29,12.5,24.2,1.2,50.0,11.0,22.0,78.0,70.0,1005.6,1003.4,12.5,18.2,Yes,No
30,12.0,24.4,0.8,39.0,17.0,17.0,48.0,28.0,1006.1,1005.1,16.9,22.7,No,No
31,11.3,26.5,0.0,56.0,19.0,31.0,46.0,26.0,1004.5,1003.2,19.7,25.7,No,No
32,9.6,23.9,0.0,41.0,19.0,11.0,44.0,22.0,1014.4,1013.1,14.9,22.1,No,No
33,10.5,28.8,0.0,26.0,11.0,7.0,43.0,22.0,1018.7,1014.8,17.1,26.5,No,No
34,12.3,34.6,0.0,37.0,6.0,17.0,41.0,12.0,1015.1,1010.3,20.7,33.9,No,No
35,12.9,35.8,0.0,41.0,6.0,26.0,41.0,9.0,1012.6,1009.2,22.4,34.4,No,No
36,13.7,37.9,0.0,52.0,4.0,26.0,33.0,8.0,1010.9,1006.7,23.1,36.8,No,No
37,16.1,38.9,0.0,57.0,6.0,30.0,34.0,12.0,1007.0,1002.7,25.2,38.4,No,No
38,14.0,28.3,0.0,48.0,17.0,24.0,43.0,15.0,1011.9,1010.9,17.9,27.6,No,No
39,12.5,28.4,0.0,37.0,20.0,9.0,38.0,16.0,1017.8,1013.7,17.2,26.6,No,No
40,17.0,30.8,0.0,37.0,15.0,11.0,36.0,24.0,1013.4,1008.1,20.2,29.3,No,No
41,16.9,32.0,0.0,31.0,13.0,17.0,52.0,31.0,1009.9,1006.8,22.8,30.0,No,No
42,17.3,34.7,0.0,35.0,7.0,15.0,48.0,16.0,1014.1,1012.1,24.2,33.2,No,No
43,17.2,37.7,0.0,35.0,7.0,17.0,51.0,19.0,1015.7,1010.9,24.3,35.7,No,No
44,17.4,43.0,0.0,39.0,7.0,17.0,40.0,8.0,1011.6,1006.9,25.6,41.5,No,No
45,19.8,32.7,0.0,44.0,20.0,28.0,34.0,28.0,1008.4,1009.2,27.6,27.1,No,No
46,14.9,26.7,0.0,56.0,20.0,31.0,46.0,20.0,1014.1,1012.7,18.0,25.5,No,No
47,10.5,28.4,0.0,33.0,19.0,11.0,35.0,16.0,1019.7,1017.4,16.0,25.8,No,No
48,11.3,32.2,0.0,28.0,17.0,15.0,34.0,17.0,1019.7,1016.2,20.9,30.5,No,No
49,13.9,36.6,0.0,39.0,2.0,15.0,39.0,10.0,1015.8,1010.6,22.0,34.4,No,No

In [33]:
df = df.fillna(df['MaxTemp'].value_counts().index[0])

In [34]:
df.isnull().sum()

MinTemp          0
MaxTemp          0
Rainfall         0
WindGustSpeed    0
WindSpeed9am     0
WindSpeed3pm     0
Humidity9am      0
Humidity3pm      0
Pressure9am      0
Pressure3pm      0
Temp9am          0
Temp3pm          0
RainToday        0
RainTomorrow     0
dtype: int64

In [35]:
df['RainToday']=pd.factorize(df['RainToday'])[0]
df['RainTomorrow']=pd.factorize(df['RainTomorrow'])[0]

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145460 entries, 0 to 145459
Data columns (total 14 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   MinTemp        145460 non-null  float64
 1   MaxTemp        145460 non-null  float64
 2   Rainfall       145460 non-null  float64
 3   WindGustSpeed  145460 non-null  float64
 4   WindSpeed9am   145460 non-null  float64
 5   WindSpeed3pm   145460 non-null  float64
 6   Humidity9am    145460 non-null  float64
 7   Humidity3pm    145460 non-null  float64
 8   Pressure9am    145460 non-null  float64
 9   Pressure3pm    145460 non-null  float64
 10  Temp9am        145460 non-null  float64
 11  Temp3pm        145460 non-null  float64
 12  RainToday      145460 non-null  int64
 13  RainTomorrow   145460 non-null  int64
dtypes: float64(12), int64(2)
memory usage: 15.5 MB

In [37]:
X=df.drop('RainTomorrow',axis=1)
y=df['RainTomorrow']

In [38]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,stratify=y,random_state=13)

In [39]:
pip install torch

Note: you may need to restart the kernel to use updated packages.

'C:\Users\Elgiz' is not recognized as an internal or external command,
operable program or batch file.

In [40]:
import torch

In [41]:
X_train=torch.from_numpy(X_train.values).float()
X_test=torch.from_numpy(X_test.values).float()
y_train=torch.from_numpy(y_train.values).float()
y_test=torch.from_numpy(y_test.values).float()

In [42]:
from torch.utils.data import TensorDataset

In [43]:
train_data=TensorDataset(X_train,y_train)
test_data=TensorDataset(X_test,y_test)

In [44]:
from torch.utils.data import DataLoader

In [45]:
train_dataloader=DataLoader(train_data,batch_size=64,shuffle=True)
test_dataloader=DataLoader(test_data,batch_size=64,shuffle=True)

In [46]:
from torch import nn

In [47]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using {} device".format(device))

class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        
        self.model = nn.Sequential(
            nn.Linear(7, 10),
            nn.ReLU(),
            nn.Linear(10, 5),
            nn.ReLU(),
            nn.Linear(5, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.model(X)

model = NeuralNetwork().to(device)

Using cpu device

In [48]:
learning_rate=0.005
batch_size=64
epochs=5

In [49]:
loss_fn=nn.BCELoss()

In [50]:
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)

In [51]:
def train_loop(dataloader,model,loss_fn,optimizer):
    size=len(dataloader.dataset)
    for batch,(X,y) in enumerate(dataloader):
        pred = model(X)
        y=y.unsqueeze(1).float()
        loss = loss_fn(pred, y)
        
        # Backpropagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if batch % 100 == 0:
            loss, current = loss.item(), batch * len(X)
            print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")

In [52]:
def test(dataloader, model):
    size = len(dataloader.dataset)
    test_loss, correct = 0, 0
    with torch.no_grad():
        for X, y in dataloader:
            pred = model(X)
            y=y.unsqueeze(1).float()
            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()
    test_loss /= size
    correct /= size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")